/*
===============================================================================
Project     : Project Phoenix
Author      : Pooja Kiran Patil
Description : Automates Stream consumption using Snowflake Task.
===============================================================================
*/

USE WAREHOUSE RETAIL_WH;
USE DATABASE PROJECT_PHOENIX;

CREATE OR REPLACE TASK SALES_MERGE_TASK

WAREHOUSE = RETAIL_WH

SCHEDULE = '1 MINUTE'

WHEN
SYSTEM$STREAM_HAS_DATA('SALES_RAW_STREAM')

AS

-- Call MERGE logic

MERGE INTO SILVER.SALES
USING RAW.SALES_RAW_STREAM
ON SILVER.SALES.SALE_ID = RAW.SALES_RAW_STREAM.SALE_ID

WHEN MATCHED THEN UPDATE SET

TOTAL_AMOUNT = RAW.SALES_RAW_STREAM.TOTAL_AMOUNT

WHEN NOT MATCHED THEN

INSERT
(
SALE_ID,
SALE_DATE,
STORE_ID,
PRODUCT_ID,
CUSTOMER_ID,
QUANTITY,
UNIT_PRICE,
TOTAL_AMOUNT
)

VALUES
(
RAW.SALES_RAW_STREAM.SALE_ID,
RAW.SALES_RAW_STREAM.SALE_DATE,
RAW.SALES_RAW_STREAM.STORE_ID,
RAW.SALES_RAW_STREAM.PRODUCT_ID,
RAW.SALES_RAW_STREAM.CUSTOMER_ID,
RAW.SALES_RAW_STREAM.QUANTITY,
RAW.SALES_RAW_STREAM.UNIT_PRICE,
RAW.SALES_RAW_STREAM.TOTAL_AMOUNT
);

-- Enable task

ALTER TASK SALES_MERGE_TASK RESUME;

-- Verify

SHOW TASKS;
